// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/partition.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/metal-stack/api/go/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PartitionServiceName is the fully-qualified name of the PartitionService service.
	PartitionServiceName = "api.v1.PartitionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PartitionServiceGetProcedure is the fully-qualified name of the PartitionService's Get RPC.
	PartitionServiceGetProcedure = "/api.v1.PartitionService/Get"
	// PartitionServiceListProcedure is the fully-qualified name of the PartitionService's List RPC.
	PartitionServiceListProcedure = "/api.v1.PartitionService/List"
	// PartitionServiceCapacityProcedure is the fully-qualified name of the PartitionService's Capacity
	// RPC.
	PartitionServiceCapacityProcedure = "/api.v1.PartitionService/Capacity"
)

// PartitionServiceClient is a client for the api.v1.PartitionService service.
type PartitionServiceClient interface {
	// Get a partition
	Get(context.Context, *connect.Request[v1.PartitionServiceGetRequest]) (*connect.Response[v1.PartitionServiceGetResponse], error)
	// List all partitions
	List(context.Context, *connect.Request[v1.PartitionServiceListRequest]) (*connect.Response[v1.PartitionServiceListResponse], error)
	// Capacity of a partitions
	Capacity(context.Context, *connect.Request[v1.PartitionServiceCapacityRequest]) (*connect.Response[v1.PartitionServiceCapacityResponse], error)
}

// NewPartitionServiceClient constructs a client for the api.v1.PartitionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPartitionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PartitionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	partitionServiceMethods := v1.File_api_v1_partition_proto.Services().ByName("PartitionService").Methods()
	return &partitionServiceClient{
		get: connect.NewClient[v1.PartitionServiceGetRequest, v1.PartitionServiceGetResponse](
			httpClient,
			baseURL+PartitionServiceGetProcedure,
			connect.WithSchema(partitionServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.PartitionServiceListRequest, v1.PartitionServiceListResponse](
			httpClient,
			baseURL+PartitionServiceListProcedure,
			connect.WithSchema(partitionServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		capacity: connect.NewClient[v1.PartitionServiceCapacityRequest, v1.PartitionServiceCapacityResponse](
			httpClient,
			baseURL+PartitionServiceCapacityProcedure,
			connect.WithSchema(partitionServiceMethods.ByName("Capacity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// partitionServiceClient implements PartitionServiceClient.
type partitionServiceClient struct {
	get      *connect.Client[v1.PartitionServiceGetRequest, v1.PartitionServiceGetResponse]
	list     *connect.Client[v1.PartitionServiceListRequest, v1.PartitionServiceListResponse]
	capacity *connect.Client[v1.PartitionServiceCapacityRequest, v1.PartitionServiceCapacityResponse]
}

// Get calls api.v1.PartitionService.Get.
func (c *partitionServiceClient) Get(ctx context.Context, req *connect.Request[v1.PartitionServiceGetRequest]) (*connect.Response[v1.PartitionServiceGetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// List calls api.v1.PartitionService.List.
func (c *partitionServiceClient) List(ctx context.Context, req *connect.Request[v1.PartitionServiceListRequest]) (*connect.Response[v1.PartitionServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Capacity calls api.v1.PartitionService.Capacity.
func (c *partitionServiceClient) Capacity(ctx context.Context, req *connect.Request[v1.PartitionServiceCapacityRequest]) (*connect.Response[v1.PartitionServiceCapacityResponse], error) {
	return c.capacity.CallUnary(ctx, req)
}

// PartitionServiceHandler is an implementation of the api.v1.PartitionService service.
type PartitionServiceHandler interface {
	// Get a partition
	Get(context.Context, *connect.Request[v1.PartitionServiceGetRequest]) (*connect.Response[v1.PartitionServiceGetResponse], error)
	// List all partitions
	List(context.Context, *connect.Request[v1.PartitionServiceListRequest]) (*connect.Response[v1.PartitionServiceListResponse], error)
	// Capacity of a partitions
	Capacity(context.Context, *connect.Request[v1.PartitionServiceCapacityRequest]) (*connect.Response[v1.PartitionServiceCapacityResponse], error)
}

// NewPartitionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPartitionServiceHandler(svc PartitionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	partitionServiceMethods := v1.File_api_v1_partition_proto.Services().ByName("PartitionService").Methods()
	partitionServiceGetHandler := connect.NewUnaryHandler(
		PartitionServiceGetProcedure,
		svc.Get,
		connect.WithSchema(partitionServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	partitionServiceListHandler := connect.NewUnaryHandler(
		PartitionServiceListProcedure,
		svc.List,
		connect.WithSchema(partitionServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	partitionServiceCapacityHandler := connect.NewUnaryHandler(
		PartitionServiceCapacityProcedure,
		svc.Capacity,
		connect.WithSchema(partitionServiceMethods.ByName("Capacity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.PartitionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PartitionServiceGetProcedure:
			partitionServiceGetHandler.ServeHTTP(w, r)
		case PartitionServiceListProcedure:
			partitionServiceListHandler.ServeHTTP(w, r)
		case PartitionServiceCapacityProcedure:
			partitionServiceCapacityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPartitionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPartitionServiceHandler struct{}

func (UnimplementedPartitionServiceHandler) Get(context.Context, *connect.Request[v1.PartitionServiceGetRequest]) (*connect.Response[v1.PartitionServiceGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PartitionService.Get is not implemented"))
}

func (UnimplementedPartitionServiceHandler) List(context.Context, *connect.Request[v1.PartitionServiceListRequest]) (*connect.Response[v1.PartitionServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PartitionService.List is not implemented"))
}

func (UnimplementedPartitionServiceHandler) Capacity(context.Context, *connect.Request[v1.PartitionServiceCapacityRequest]) (*connect.Response[v1.PartitionServiceCapacityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PartitionService.Capacity is not implemented"))
}
