// Code generated discover.go. DO NOT EDIT.
package permissions

func GetServices() []string {
	return []string{
		"admin.v1.TenantService",
		"admin.v1.TokenService",
		"api.v1.HealthService",
		"api.v1.IPService",
		"api.v1.MethodService",
		"api.v1.PartitionService",
		"api.v1.ProjectService",
		"api.v1.TenantService",
		"api.v1.TokenService",
		"api.v1.UserService",
		"api.v1.VersionService",
	}
}

func GetServicePermissions() *ServicePermissions {
	return &ServicePermissions{
		Roles: Roles{
			Admin: Admin{
				"ADMIN_ROLE_EDITOR": []string{
					"/admin.v1.TenantService/List",
					"/admin.v1.TokenService/List",
					"/admin.v1.TokenService/Revoke",
				},
				"ADMIN_ROLE_VIEWER": []string{
					"/admin.v1.TenantService/List",
					"/admin.v1.TokenService/List",
				},
			},
			Tenant: Tenant{
				"TENANT_ROLE_EDITOR": []string{
					"/api.v1.ProjectService/Create",
					"/api.v1.TenantService/Get",
					"/api.v1.TenantService/Update",
					"/api.v1.TenantService/Delete",
				},
				"TENANT_ROLE_GUEST": []string{
					"/api.v1.TenantService/Get",
				},
				"TENANT_ROLE_OWNER": []string{
					"/api.v1.ProjectService/Create",
					"/api.v1.TenantService/Get",
					"/api.v1.TenantService/Update",
					"/api.v1.TenantService/Delete",
					"/api.v1.TenantService/RemoveMember",
					"/api.v1.TenantService/UpdateMember",
					"/api.v1.TenantService/Invite",
					"/api.v1.TenantService/InviteDelete",
					"/api.v1.TenantService/InvitesList",
				},
				"TENANT_ROLE_VIEWER": []string{
					"/api.v1.TenantService/Get",
				},
			},
			Project: Project{
				"PROJECT_ROLE_EDITOR": []string{
					"/api.v1.IPService/Get",
					"/api.v1.IPService/Allocate",
					"/api.v1.IPService/Update",
					"/api.v1.IPService/List",
					"/api.v1.IPService/Delete",
					"/api.v1.ProjectService/Get",
					"/api.v1.ProjectService/Update",
				},
				"PROJECT_ROLE_OWNER": []string{
					"/api.v1.IPService/Get",
					"/api.v1.IPService/Allocate",
					"/api.v1.IPService/Update",
					"/api.v1.IPService/List",
					"/api.v1.IPService/Delete",
					"/api.v1.ProjectService/Get",
					"/api.v1.ProjectService/Delete",
					"/api.v1.ProjectService/Update",
					"/api.v1.ProjectService/RemoveMember",
					"/api.v1.ProjectService/UpdateMember",
					"/api.v1.ProjectService/Invite",
					"/api.v1.ProjectService/InviteDelete",
					"/api.v1.ProjectService/InvitesList",
				},
				"PROJECT_ROLE_VIEWER": []string{
					"/api.v1.IPService/Get",
					"/api.v1.IPService/List",
					"/api.v1.ProjectService/Get",
				},
			},
		},
		Methods: map[string]bool{
			"/admin.v1.TenantService/List":          true,
			"/admin.v1.TokenService/List":           true,
			"/admin.v1.TokenService/Revoke":         true,
			"/api.v1.HealthService/Get":             true,
			"/api.v1.IPService/Allocate":            true,
			"/api.v1.IPService/Delete":              true,
			"/api.v1.IPService/Get":                 true,
			"/api.v1.IPService/List":                true,
			"/api.v1.IPService/Update":              true,
			"/api.v1.MethodService/List":            true,
			"/api.v1.MethodService/TokenScopedList": true,
			"/api.v1.PartitionService/Capacity":     true,
			"/api.v1.PartitionService/Get":          true,
			"/api.v1.PartitionService/List":         true,
			"/api.v1.ProjectService/Create":         true,
			"/api.v1.ProjectService/Delete":         true,
			"/api.v1.ProjectService/Get":            true,
			"/api.v1.ProjectService/Invite":         true,
			"/api.v1.ProjectService/InviteAccept":   true,
			"/api.v1.ProjectService/InviteDelete":   true,
			"/api.v1.ProjectService/InviteGet":      true,
			"/api.v1.ProjectService/InvitesList":    true,
			"/api.v1.ProjectService/List":           true,
			"/api.v1.ProjectService/RemoveMember":   true,
			"/api.v1.ProjectService/Update":         true,
			"/api.v1.ProjectService/UpdateMember":   true,
			"/api.v1.TenantService/Create":          true,
			"/api.v1.TenantService/Delete":          true,
			"/api.v1.TenantService/Get":             true,
			"/api.v1.TenantService/Invite":          true,
			"/api.v1.TenantService/InviteAccept":    true,
			"/api.v1.TenantService/InviteDelete":    true,
			"/api.v1.TenantService/InviteGet":       true,
			"/api.v1.TenantService/InvitesList":     true,
			"/api.v1.TenantService/List":            true,
			"/api.v1.TenantService/RemoveMember":    true,
			"/api.v1.TenantService/Update":          true,
			"/api.v1.TenantService/UpdateMember":    true,
			"/api.v1.TokenService/Create":           true,
			"/api.v1.TokenService/Get":              true,
			"/api.v1.TokenService/List":             true,
			"/api.v1.TokenService/Revoke":           true,
			"/api.v1.TokenService/Update":           true,
			"/api.v1.UserService/Get":               true,
			"/api.v1.VersionService/Get":            true,
		},
		Visibility: Visibility{
			Public: map[string]bool{
				"/api.v1.HealthService/Get":                                      true,
				"/api.v1.MethodService/List":                                     true,
				"/api.v1.VersionService/Get":                                     true,
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      true,
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": true,
			},
			Self: map[string]bool{
				"/api.v1.MethodService/TokenScopedList": true,
				"/api.v1.PartitionService/Capacity":     true,
				"/api.v1.PartitionService/Get":          true,
				"/api.v1.PartitionService/List":         true,
				"/api.v1.ProjectService/InviteAccept":   true,
				"/api.v1.ProjectService/InviteGet":      true,
				"/api.v1.ProjectService/List":           true,
				"/api.v1.TenantService/Create":          true,
				"/api.v1.TenantService/InviteAccept":    true,
				"/api.v1.TenantService/InviteGet":       true,
				"/api.v1.TenantService/List":            true,
				"/api.v1.TokenService/Create":           true,
				"/api.v1.TokenService/Get":              true,
				"/api.v1.TokenService/List":             true,
				"/api.v1.TokenService/Revoke":           true,
				"/api.v1.TokenService/Update":           true,
				"/api.v1.UserService/Get":               true,
			},
		},
		Auditable: map[string]bool{
			"/admin.v1.TenantService/List":          true,
			"/admin.v1.TokenService/List":           true,
			"/admin.v1.TokenService/Revoke":         true,
			"/api.v1.HealthService/Get":             false,
			"/api.v1.IPService/Allocate":            true,
			"/api.v1.IPService/Delete":              true,
			"/api.v1.IPService/Get":                 false,
			"/api.v1.IPService/List":                false,
			"/api.v1.IPService/Update":              true,
			"/api.v1.MethodService/List":            true,
			"/api.v1.MethodService/TokenScopedList": true,
			"/api.v1.PartitionService/Capacity":     false,
			"/api.v1.PartitionService/Get":          false,
			"/api.v1.PartitionService/List":         false,
			"/api.v1.ProjectService/Create":         true,
			"/api.v1.ProjectService/Delete":         true,
			"/api.v1.ProjectService/Get":            false,
			"/api.v1.ProjectService/Invite":         true,
			"/api.v1.ProjectService/InviteAccept":   true,
			"/api.v1.ProjectService/InviteDelete":   true,
			"/api.v1.ProjectService/InviteGet":      false,
			"/api.v1.ProjectService/InvitesList":    false,
			"/api.v1.ProjectService/List":           false,
			"/api.v1.ProjectService/RemoveMember":   true,
			"/api.v1.ProjectService/Update":         true,
			"/api.v1.ProjectService/UpdateMember":   true,
			"/api.v1.TenantService/Create":          true,
			"/api.v1.TenantService/Delete":          true,
			"/api.v1.TenantService/Get":             false,
			"/api.v1.TenantService/Invite":          true,
			"/api.v1.TenantService/InviteAccept":    true,
			"/api.v1.TenantService/InviteDelete":    true,
			"/api.v1.TenantService/InviteGet":       false,
			"/api.v1.TenantService/InvitesList":     false,
			"/api.v1.TenantService/List":            false,
			"/api.v1.TenantService/RemoveMember":    true,
			"/api.v1.TenantService/Update":          true,
			"/api.v1.TenantService/UpdateMember":    true,
			"/api.v1.TokenService/Create":           true,
			"/api.v1.TokenService/Get":              true,
			"/api.v1.TokenService/List":             true,
			"/api.v1.TokenService/Revoke":           true,
			"/api.v1.TokenService/Update":           true,
			"/api.v1.UserService/Get":               true,
			"/api.v1.VersionService/Get":            false,
		},
	}
}
